import type { Metadata } from "next";
import "./globals.css";

import { Syne } from 'next/font/google'

const syne = Syne({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'],
  variable: '--font-syne',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Ghulam",
  description: "Generated by Al Ghulam",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={syne.variable}>
      <body
        className={`antialiased bg-zinc-100`}
      >
        {children}
      </body>
    </html>
  );
}
