/**
 * Application-specific configuration
 * Customize these values for each new project
 */

export const appConfig = {
  // Application identity
  name: "AppName",
  description: "Generated by Al AppName",
  
  // Branding
  branding: {
    companyName: "AppName",
    footer: "Github",
  },

  // Feature flags
  features: {
    notifications: true,
    search: true,
    userProfile: true,
  },

  // UI Configuration
  ui: {
    maxWidth: "lg:max-w-7xl xl:max-w-[120rem]",
    sidebarWidth: "w-40",
  },
} as const;
